services:
  - type: web
    name: inventory-management-system
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 